core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'
urlpatterns = [
    path('', about, name='about'),
    path('register/', newRegister, name='register'),
    path('newRegister/', newRegister, name='newRegister'),
    path('register/verifymail', verify_mail, name='verify_mail'),
    path('register/verifyusername', verify_username, name='verify_username'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('accounts/social/signup/', social_register, name='social-register'),
    path('user-verification/', user_verification, name='user-verification'),
]

elemental/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from elemental import settings

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('members/', include('members.urls', namespace='members')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('notes/', include('notes.urls', namespace='notes')),
    path('el3m3nt4l/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path

from members.views import *

app_name = 'members'
urlpatterns = [
    path('miembros/', MemberListView.as_view(), name='miembros'),
    path('miembros/skills/', MemberSkillView.as_view(), name='miembros-skills'),
    path('miembros/skills/<slug:category>/', MemberSkillView.as_view(), name='miembros-skills-categoria'),
    path('miembros/skills/<slug:category>/<slug:skill>', MemberSkillView.as_view(), name='miembros-skills-particular'),
    path('miembros/intereses/', MemberInterestView.as_view(), name='miembros-intereses'),
    path('miembros/intereses/<slug:category>/', MemberInterestView.as_view(), name='miembros-intereses-categoria'),
    path('miembros/intereses/<slug:category>/<slug:interest>', MemberInterestView.as_view(), name='miembros-intereses-particular'),
    path('miembros/filtro/', MemberAdvancedFilterView.as_view(), name='member-filter'),
    path('miembro/<slug>/', MemberDetailView.as_view(), name='miembro'),
    path('add-tags/<slug:designation>/<slug:category>', MemberAddTagView.as_view(), name='add-tags'),
    path('delete-tags/', MemberDeleteTagView.as_view(), name='delete-tags'),
    path('add-skill/<slug:tag>/', add_skill, name='add-skill'),
    path('delete-interest/<slug:tag>', delete_interest, name='delete-interest'),
    path('add-interest/<slug:tag>/', add_interest, name='add-interest'),
    path('delete-skill/<slug:tag>', delete_skill, name='delete-skill'),
    path('update-user/', update_user, name='update-user'),
    path('getSkills/',  get_skill_for_register, name='get_skill_for_register'),
    path('getInterest/', get_interest_for_register, name='get_skill_for_register'),
]

notes/urls.py
from django.urls import path

from notes.views import *

app_name = 'notes'
urlpatterns = [
    path("peticiones/", PetitionListView.as_view(), name="peticiones"),
    path("authorize-petition/<slug>/", authorize_petition, name='authorize-petition'),
    path("deny-petition/<slug>/", deny_petition, name='deny-petition'),
    path("cancel-petition/<slug>/", cancel_petition, name='cancel-petition'),
    path("delete-notification/<slug>/", delete_notification, name="delete-notification"),
    path("miembro/<slug>/send-invitation/", send_invitation_project, name='send-invitation-project'),
]

projects/urls.py
from django.urls import path

from projects.views import *

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='proyectos'),
    path('intereses/', ProjectListView.as_view(), name='proyectos-intereses'),
    path('intereses/<slug:category>/', ProjectInterestView.as_view(), name='proyectos-intereses-categoria'),
    path('intereses/<slug:category>/<slug:interest>/', ProjectInterestView.as_view(), name='proyectos-intereses-particular'),
    path('add-project/', add_project, name='add-project'),
    path('update-project/<slug>/', update_project, name='update-project'),
    path('delete-project/<slug>/', delete_project, name='delete-project'),
    path('project-add-tags/<slug:project_slug>/<slug:category>', ProjectAddTagView.as_view(), name='project-add-tags'),
    path('project-add-interest/<slug:project_slug>/<slug:tag>/', project_add_interest, name='project-add-interest'),
    path('project-delete-tags/<slug>', ProjectDeleteTagView.as_view(), name='project-delete-tags'),
    path('project-delete-interest/<slug:project_slug>/<slug:tag>/', project_delete_interest, name='project-delete-interest'),
    path('proyectos/filtro/', ProjectAdvancedFilterView.as_view(), name='project-filter'),
    path('delete-assignation/<slug>/', delete_assignation, name='delete-assignation'),
    path('join-project/<slug>/', join_project, name='join-project'),
    path('<slug>/', ProjectDetailView.as_view(), name='proyecto'),
    path('<slug>/miembros/', ProjectNewMembersView.as_view(), name='project-find-members'),
]

members/forms.py
from django.forms import ModelForm
from .models import Member


class MemberFileForm(ModelForm):
    class Meta:
        model = Member
        fields = ['image', 'resume']

members/views.py
from django.contrib import messages
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.utils.datastructures import MultiValueDictKeyError
from django.views import generic
from rest_framework.decorators import api_view

from core.models import SkillCategory, Skill, InterestCategory, Interest
from core.serializers import SkillsSerializer, InterestSerializer
from projects.models import Assignation
from .aux import add_skill_generic, add_interest_generic
from .forms import MemberFileForm
from .models import Member, MemberInterest, MemberSkill, MemberSkillCategory, MemberInterestCategory


class MemberListView(generic.ListView):
    model = Member
    paginate_by = 9
    template_name = 'members/miembros.html'


class MemberInterestView(generic.View):
    def get(self, request, category='computacion', interest=None):
        top_categories = InterestCategory.objects.filter(top=True)
        non_top_categories = InterestCategory.objects.filter(top=False)
        current_category = InterestCategory.objects.get(slug=category)
        top_interests = Interest.objects.filter(category=current_category).filter(top_category=True)
        non_top_interests = Interest.objects.filter(category=current_category).filter(top_category=False)
        if interest is not None:
            members = MemberInterest.objects.filter(category_slug=category).filter(interest_slug=interest)
        else:
            members = MemberInterestCategory.objects.filter(category=current_category)
        filter_used = 'intereses'
        filter_interest = True
        paginator = Paginator(members, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'top_categories': top_categories,
            'top_interests': top_interests,
            'non_top_categories': non_top_categories,
            'non_top_interests': non_top_interests,
            'filter_used': filter_used,
            'filter_interest': filter_interest,
        }
        return render(request, 'members/miembros_filter.html', context)


class MemberSkillView(generic.View):
    def get(self, request, category='programacion', skill=None):
        top_categories = SkillCategory.objects.filter(top=True)
        non_top_categories = SkillCategory.objects.filter(top=False)
        current_category = SkillCategory.objects.get(slug=category)
        top_skills = Skill.objects.filter(category=current_category).filter(top_category=True)
        non_top_skills = Skill.objects.filter(category=current_category).filter(top_category=False)
        if skill is not None:
            members = MemberSkill.objects.filter(category_slug=category).filter(skill_slug=skill)
        else:
            members = MemberSkillCategory.objects.filter(category=current_category)
        filter_used = 'skills'
        filter_interest = False
        paginator = Paginator(members, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'page_obj': page_obj,
            'top_categories': top_categories,
            'top_interests': top_skills,
            'non_top_categories': non_top_categories,
            'non_top_interests': non_top_skills,
            'filter_used': filter_used,
            'filter_interest': filter_interest,
        }
        return render(request, 'members/miembros_filter.html', context)


class MemberAdvancedFilterView(generic.View):
    _interest_categories = InterestCategory.objects.all()
    _skill_categories = SkillCategory.objects.all()
    interest_categories = []
    skill_categories = []

    for interest_category in _interest_categories:
        x = []
        x.append(False)
        x.append(interest_category)
        interest_categories.append(x)

    for skill_category in _skill_categories:
        x = []
        x.append(False)
        x.append(skill_category)
        skill_categories.append(x)

    def get(self, request):
        selected_interest_categories = []
        selected_skill_categories = []
        for i in range(0, len(self.interest_categories)):
            try:
                interest = self.interest_categories[i][1]
                if request.GET[interest.slug]:
                    self.interest_categories[i][0] = True
                    selected_interest_categories.append(interest)
            except MultiValueDictKeyError:
                self.interest_categories[i][0] = False
                print('none')
        for i in range(0, len(self.skill_categories)):
            try:
                skill = self.skill_categories[i][1]
                if request.GET[skill.slug]:
                    self.skill_categories[i][0] = True
                    selected_skill_categories.append(skill)
            except MultiValueDictKeyError:
                self.skill_categories[i][0] = False
                print('none')

        interests_groups = []
        for selected_interest_category in selected_interest_categories:
            interests_groups.append(Interest.objects.filter(category=selected_interest_category))
        skills_groups = []
        for selected_skill_category in selected_skill_categories:
            skills_groups.append(Skill.objects.filter(category=selected_skill_category))

        selected_interests = []
        for interest_group in interests_groups:
            for interest in interest_group:
                try:
                    if request.GET[interest.slug]:
                        selected_interests.append(interest)
                except MultiValueDictKeyError:
                    print('none')
        selected_skills = []
        for skill_group in skills_groups:
            for skill in skill_group:
                try:
                    if request.GET[skill.slug]:
                        selected_skills.append(skill)
                except MultiValueDictKeyError:
                    print('none')
        members_groups = []
        for selected_interest in selected_interests:
            members_groups.append(MemberInterest.objects.filter(interest=selected_interest))
        for selected_skill in selected_skills:
            members_groups.append(MemberSkill.objects.filter(skill=selected_skill))

        members = []
        for member_group in members_groups:
            for memberTag in member_group:
                if memberTag.member not in members:
                    members.append(memberTag.member)
        paginator = Paginator(members, 18)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'interest_categories': self.interest_categories,
            'skill_categories': self.skill_categories,
            'interests_groups': interests_groups,
            'skills_groups': skills_groups,
            'page_obj': page_obj,
        }
        return render(request, 'members/miembro_filtro_avanzado.html', context)


class MemberDetailView(generic.View):
    def get(self, request, slug, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, 'Debes iniciar sesión para ver más sobre un usuario')
            return redirect('core:login')
        try:
            member = Member.objects.get(slug=slug)
        except:
            return redirect('members:miembros')
        assignations = Assignation.objects.filter(user=member.user)
        user = get_user(request)
        author = False
        if user == member.user:
            author = True
        interests = MemberInterest.objects.filter(member=member)
        skills = MemberSkill.objects.filter(member=member)
        context = {
            'object': member,
            'assignations': assignations,
            'author': author,
            'interests': interests,
            'skills': skills,
        }
        return render(request, 'members/miembro.html', context)


class MemberAddTagView(LoginRequiredMixin, generic.View):
    def get(self, request, designation='intereses', category='computacion'):
        user = get_user(request)
        member = Member.objects.get(user=user)
        new_tags = []
        if designation == 'intereses':
            designation_is_interests = True
            categories = InterestCategory.objects.all()
            tag_category = InterestCategory.objects.get(slug=category)
            tags = Interest.objects.filter(category=tag_category)
            old_tags = MemberInterest.objects.filter(category_slug=category).filter(member=member)
            if old_tags.count() == 0:
                new_tags = tags
            else:
                for tag in tags:
                    for old_tag in old_tags:
                        if old_tag.interest != tag:
                            new_tags.append(tag)
        if designation == 'skills':
            designation_is_interests = False
            categories = SkillCategory.objects.all()
            tag_category = SkillCategory.objects.get(slug=category)
            tags = Skill.objects.filter(category=tag_category)
            old_tags = MemberSkill.objects.filter(category_slug=category).filter(member=member)
            if old_tags.count() == 0:
                new_tags = tags
            else:
                for tag in tags:
                    for old_tag in old_tags:
                        if old_tag.skill != tag:
                            new_tags.append(tag)
        context = {
            'categories': categories,
            'tags': new_tags,
            'current_designation': designation,
            'current_category': category,
            'designation_is_interests': designation_is_interests,
        }

templates/members/delete_tags_user.html
{% extends "base.html" %}

{% block content %}
<br><br><br>
  <section class="pb_section pb_slant-light" id="section-pasos">
    <div class="container">
      <div style="margin-bottom: 10px !important; height: 80px !important;" class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>{{member.name}}</strong></h5>
          <h2>Mis Tags</h2>
          <h6><a class="filter" href="{{member.get_absolute_url}}">Ir a mi perfil</a></h6>
        </div>
      </div>
      <div style="margin-top: 20px !important; margin-bottom: 10px !important; height: 80px !important; text-align: center;" class="row justify-content-center">
        <div class="col-2"></div>
        <div class="col-8">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'members:add-tags' designation='intereses' category='computacion' %}">
            Ir a Nuevos Tags
          </a>
        </div>
        <div class="col-2"></div>

      </div>
      <div class="row">
      <div class="col-6">
        <h3>Interests</h3>
      </div>
      <div class="col-6">
        <h3>Skills</h3>
      </div>
      </div>
      <div class="row">
        <div class="col-6">
          <div class="row">
            {% for my_tag in interests %}
        
        <div class="col-lg-4 col-md- col-sm-6">
          <div class="media d-block pb_feature-v1 text-left">

          <div class="card card-square" style="width: 18rem;">
                <img class="card-img-top" src="..." alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ my_tag.get_tag_name }}</h5>
                  <a href="{{ my_tag.get_delete_url }}" class="btn btn-warning">Borrar</a>
                </div>
              </div>
          </div>
        </div>
        {% endfor %}
          </div>
        </div>
        <div class="col-6">
          <div class="row">
            {% for my_tag in skills %}
        
        <div class="col-lg-4 col-md- col-sm-6">
          <div class="media d-block pb_feature-v1 text-left">

          <div class="card card-square" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{ my_tag.get_tag_name }}</h5>
                  <a href="{{ my_tag.get_delete_url }}" class="btn btn-warning">Borrar</a>
                </div>
              </div>
          </div>
        </div>
        {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/members/miembros.html
{% extends "base.html" %}

{% block content %}
<section class="pb_cover_v3 overflow-hidden cover-bg-opacity text-left  pb_slant-light green-background" id="section-home">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-6">
          <h2 class="heading mb-3">Nuestra comunidad</h2>
          <div class="sub-heading">
            {% if user.is_authenticated %}
            <p class="mb-4">¿Buscas estudiantes universitarios para un proyecto?</p>
            <p class="mb-4">1. Busca el perfil que desees</p>
            <p class="mb-4">2. Revisa su información de contacto</p>
            <p class="mb-4">3. ¡Conócelo! </p>
            <br>
          {% else %}
          <p class="mb-4">¿Buscas estudiantes universitarios para un proyecto?</p>
          <p class="mb-4">1. Busca el perfil que desees</p>
          <p class="mb-4">2. Revisa su información de contacto</p>
          <p class="mb-4">3. ¡Conócelo! </p>
          <br>
          <p class="mb-4">¿Aún no formas parte? ¡Únete!</p>
          <p class="mb-5"><a class="btn btn-success btn-lg pb_btn-pill smoothscroll" href="{% url 'projects:add-project' %}"><span class="pb_font-14 text-uppercase pb_letter-spacing-1">Crear</span></a></p>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="anchor" class="pb_section pb_slant-light" id="section-pasos">
    <div class="container">
      <div style="margin-bottom: 10px !important; height: 80px !important;" class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>La comunidad</strong></h5>
          <h2>Todos los miembros</h2>
        </div>
      </div>
      <div style="margin-top: 20px !important; margin-bottom: 10px !important; height: 80px !important; text-align: center;" class="row justify-content-center">
        <div class="col-2"></div>
        <div class="col-4">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'members:miembros-intereses' %}#anchor-filter">
            Intereses
          </a>
        </div>
        <div class="col-4">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'members:miembros-skills' %}#anchor-filter">
            Skills
          </a>
        </div>
        <div class="col-2"></div>
      </div>
      <div style="margin-bottom: 20px !important; text-align: center;" class="hide-desktop row justify-content-center">
        <div class="col-2"></div>
        <div class="col-8">
          <a class="filter text-xs mb-2" href="{% url 'members:member-filter' %}">
            Búsqueda avanzada
          </a>
        </div>
        <div class="col-2"></div>
      </div>
      <div class="row">
        <div class="col-2 border-left hide-mobile">
          <h6><a class="filter text-xs mb-2" href="{% url 'members:member-filter' %}">Búsqueda Avanzada</a></h6>
        </div>
        <div class="col-2 hide-desktop"></div>
        <div class="col-8">
          <div class="row">
            {% for member in object_list %}
        
        <div class="col-lg-4 col-md- col-sm-6">
          <div class="media d-block pb_feature-v1 text-left">

            <div class="card">
              {% if member.image %}
                  <img style="margin: auto; height: 200px; width: 200px; max-width: 100%;"  class="card-img-top" src="{{member.image.url}}" alt="Imagen de {{member.name}}">
              {% else %}
              <img style="margin: auto; height: 200px; width: 200px; max-width: 100%;"  class="card-img-top" src="imagen_predeterminada.png}" alt="Imagen de {{member.name}}">            
                  {% endif %}
                  <div class="card-body">
                    <div class="card-title">{{ member.name }}</div>
                    <div style="font-size: smaller;" class="card-text">
                        {{ member.summary }}
                    </div>
                    <br>
                    <div style="margin: 0 auto; width: 100%;" class="card-text"><a class="btn btn-success" href="{{member.get_absolute_url}}">Conocer</a></div>
                    <br>
                  </div>
            </div>

          </div>
        </div>
        {% endfor %}
          </div>
        </div>
        <div class="col-2 border-right">
        </div>
        
      </div>
      <br>
      <br>
      <div style="display: flex; justify-content: center; align-items: center;" class="pagination ali">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a style="color: #47b55d" href="?page=1#anchor">&laquo; first</a>
                <a style="color:#47b55d" href="?page={{ page_obj.previous_page_number }}#anchor">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a style="color:#47b55d" href="?page={{ page_obj.next_page_number }}#anchor">next</a>
                <a style="color:#47b55d" href="?page={{ page_obj.paginator.num_pages }}#anchor">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
  </section>

{% endblock content %}

templates/members/miembros_filter.html
{% extends "base.html" %}

{% block content %}
<section class="pb_cover_v3 overflow-hidden cover-bg-opacity text-left  pb_slant-light green-background" id="section-home">
    <div class="container">
      <a href="#anchor-filter"></a>
      <div class="row align-items-center justify-content-center">
        <div class="col-md-6">
          <h2 class="heading mb-3">Nuestra comunidad</h2>
          <div class="sub-heading">
            {% if user.is_authenticated %}
            <p class="mb-4">¿Buscas estudiantes universitarios para un proyecto?</p>
            <p class="mb-4">1. Busca el perfil que desees</p>
            <p class="mb-4">2. Revisa su información de contacto</p>
            <p class="mb-4">3. ¡Conócelo! </p>
            <br>
          {% else %}
          <p class="mb-4">¿Buscas estudiantes universitarios para un proyecto?</p>
          <p class="mb-4">1. Busca el perfil que desees</p>
          <p class="mb-4">2. Revisa su información de contacto</p>
          <p class="mb-4">3. ¡Conócelo! </p>
          <br>
          <p class="mb-4">¿Aún no formas parte? ¡Únete!</p>
          <p class="mb-5"><a class="btn btn-success btn-lg pb_btn-pill smoothscroll" href="/add-project"><span class="pb_font-14 text-uppercase pb_letter-spacing-1">Crear</span></a></p>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>


  <section id="anchor-filter" class="pb_section pb_slant-light" id="section-pasos">
    <div class="container">
      <div style="margin-bottom: 10px !important; height: 80px !important;" class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>La comunidad</strong></h5>
          <h2>Miembros por {{filter_used}}</h2>
        </div>
      </div>
      <div style="margin-top: 20px !important; margin-bottom: 10px !important; height: 80px !important; text-align: center;" class="row justify-content-center">
        <div class="col-2"></div>
        {% if filter_interest %}
        <div class="col-8">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'members:miembros-skills' %}#anchor-filter">
            Ir a Skills
          </a>
        </div>
        {% else %}
        <div class="col-8">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'members:miembros-intereses' %}#anchor-filter">
            Ir a Intereses
          </a>
        </div>
        {% endif %}
        <div class="col-2"></div>
      </div>
      {% if top_interests %}
      <div style="margin-bottom: 10px !important; height: 80px !important; text-align: center;" class="hide-mobile row justify-content-center">
        <div class="col-2"></div>
        {% for interest in top_interests %}
        <div class="col-2">
          <a class="filter text-uppercase text-xs mb-2" href="{{interest.get_member_interest_url}}#anchor-filter">
            {{ interest.name }}
          </a>
        </div>
        {% endfor %}
        <div class="col-2">
          {% if non_top_interests %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Más
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for interest in non_top_interests %}
              <a class="dropdown-item" href="{{interest.get_project_interest_url}}">{{interest.name}}</a>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        </div>
      </div>
      {% endif %}
      
      <div style="margin: auto;" class="row">
        <div id="navbarmobile" class="hide-desktop">
          {% if top_categories %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorías
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a style="color:#47b55d;" class="dropdown-item" href="{% url 'projects:project-filter' %}">Búsqueda Avanzada</a>
              {% for category in top_categories %}
              <a class="dropdown-item" href="{{category.get_project_category_url}}#anchor-filter">{{category.name}}</a>
              {% endfor %}
  
            </div>
          </div>
          {% endif %}
          <br>
        </div>
      </div> 


      <div class="row">
        <div class="col-2 border-left hide-mobile">
              
          <!-- Title -->
          <h6><a class="filter text-xs mb-2" href="{% url 'members:member-filter' %}">Búsqueda Avanzada</a></h6>
          <h6 class="title">
            Categorías
          </h6>
    
          <!-- Sidenav -->
          <nav class="sidenav d-flex flex-column mb-5 mb-md-0">
            {% for category in top_categories %}
            <a class="filter text-uppercase text-xs mb-2" href="{{ category.get_member_category_url }}#anchor-filter">
              {{category.name}}
            </a>
            {% endfor %}
          </nav>
          {% if non_top_categories %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Otros
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for category in non_top_categories %}
              <a class="dropdown-item" href="{{category.get_project_category_url}}#anchor-filter">{{category.name}}</a>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        </div>
        <div class="col-2 hide-desktop"></div>
        <div class="col-8">
          <div class="row">
            {% if page_obj %}
            {% for member_filter in page_obj %}
        
        <div class="col-lg-4 col-md-6 col-sm-12">
          <div class="media d-block pb_feature-v1 text-left">

          <div class="card card-square" style="width: 18rem;">
            {%if member_filter.member.image%}
                <img class="card-img-top" src="{{member_filter.member.image.url}}" alt="Imagen de {{member_filter.member.name}}">
              {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{ member_filter.member.name }}</h5>
                  <p class="card-text">{{ member_filter.member.summary }}</p>
                  <br>
                    <div style="margin: 0 auto; width: 100%;" class="card-text"><a class="btn btn-success" href="{{ member_filter.member.get_absolute_url }}">Conocer</a></div>
                    <br>
                </div>
              </div>

          </div>
        </div>
        {% endfor %}
        {% else %}
        <div style="height: 200px;" class="container">
          <h3>Por el momento no hay miembros que coincidan con tu búsqueda...</h3>
        </div>
        {% endif %}
          </div>
        </div>
        <div class="col-2 border-right">
        </div>
        
      </div>
      <br>
      <br>
      <div style="display: flex; justify-content: center; align-items: center;" class="pagination ali">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a style="color: #47b55d" href="?page=1#anchor-filter">&laquo; first</a>
                <a style="color:#47b55d" href="?page={{ page_obj.previous_page_number }}#anchor-filter">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a style="color:#47b55d" href="?page={{ page_obj.next_page_number }}#anchor-filter">next</a>
                <a style="color:#47b55d" href="?page={{ page_obj.paginator.num_pages }}#anchor-filter">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
  </section>

{% endblock content %}