core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'
urlpatterns = [
    path('', about, name='about'),
    path('register/', newRegister, name='register'),
    path('newRegister/', newRegister, name='newRegister'),
    path('register/verifymail', verify_mail, name='verify_mail'),
    path('register/verifyusername', verify_username, name='verify_username'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('accounts/social/signup/', social_register, name='social-register'),
    path('user-verification/', user_verification, name='user-verification'),
]

elemental/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from elemental import settings

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('members/', include('members.urls', namespace='members')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('notes/', include('notes.urls', namespace='notes')),
    path('el3m3nt4l/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from projects.views import *

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='proyectos'),
    path('intereses/', ProjectListView.as_view(), name='proyectos-intereses'),
    path('intereses/<slug:category>/', ProjectInterestView.as_view(), name='proyectos-intereses-categoria'),
    path('intereses/<slug:category>/<slug:interest>/', ProjectInterestView.as_view(), name='proyectos-intereses-particular'),
    path('add-project/', add_project, name='add-project'),
    path('update-project/<slug>/', update_project, name='update-project'),
    path('delete-project/<slug>/', delete_project, name='delete-project'),
    path('project-add-tags/<slug:project_slug>/<slug:category>', ProjectAddTagView.as_view(), name='project-add-tags'),
    path('project-add-interest/<slug:project_slug>/<slug:tag>/', project_add_interest, name='project-add-interest'),
    path('project-delete-tags/<slug>', ProjectDeleteTagView.as_view(), name='project-delete-tags'),
    path('project-delete-interest/<slug:project_slug>/<slug:tag>/', project_delete_interest, name='project-delete-interest'),
    path('proyectos/filtro/', ProjectAdvancedFilterView.as_view(), name='project-filter'),
    path('delete-assignation/<slug>/', delete_assignation, name='delete-assignation'),
    path('join-project/<slug>/', join_project, name='join-project'),
    path('<slug>/', ProjectDetailView.as_view(), name='proyecto'),
    path('<slug>/miembros/', ProjectNewMembersView.as_view(), name='project-find-members'),
]

projects/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
import datetime

from core.aux import validate_file_size
from core.models import Interest, InterestCategory, Skill, SkillCategory


class Project(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.IntegerField(unique=True)
    title = models.CharField(max_length=100)
    start_date = models.DateTimeField("date created", auto_now_add=True)
    project_date = models.DateTimeField("since", blank=True, default=datetime.date.today)
    summary = models.CharField(max_length=140)
    description = models.TextField()
    status = models.CharField(max_length=140, default="En desarrollo")
    active = models.BooleanField(default=True)
    description_candidate = models.CharField(max_length=256, default="")
    timeline = models.CharField(max_length=2048, default="[]")
    image = models.ImageField(upload_to="img/projects", blank=True, validators=[validate_file_size])

    class Meta:
        ordering = ['-slug']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("projects:proyecto", kwargs={
            'slug': self.slug
        })

    def get_update_project_url(self):
        return reverse("projects:update-project", kwargs={
            'slug': self.slug
        })

    def get_delete_project_url(self):
        return reverse("projects:delete-project", kwargs={
            'slug': self.slug
        })

    def get_join_project_url(self):
        return reverse("projects:join-project", kwargs={
            'slug': self.slug
        })


class ProjectInterest(models.Model):
    slug = models.IntegerField(unique=True)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    category_slug = models.CharField(max_length=30, default='')
    interest_slug = models.CharField(max_length=30, default='')

    class Meta:
        ordering = ['-slug']

    def __str__(self):
        return str(self.project.title) + "-" + str(self.interest.name)

    def get_delete_url(self):
        return reverse("projects:project-delete-interest", kwargs={
            'project_slug': self.project.slug,
            'tag': self.slug,
        })

    def get_tag_name(self):
        return self.interest.name


class ProjectInterestCategory(models.Model):
    slug = models.IntegerField(unique=True)
    category = models.ForeignKey(InterestCategory, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-slug']

    def __str__(self):
        return str(self.project.title) + "-" + str(self.category.name)


class Assignation(models.Model):
    slug = models.IntegerField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-slug']

    def __str__(self):
        return self.user.username + "-" + self.project.title

    def get_delete_assignation_url(self):
        return reverse("projects:delete-assignation", kwargs={
            'slug': self.slug
        })

projects/forms.py
from django.forms import ModelForm
from .models import Project


class ProjectFileForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image']

projects/views.py
from django.contrib import messages
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError
from django.views import generic

from core.aux import generate_slug
from core.models import InterestCategory, Interest
from members.models import Member, MemberInterest
from notes.models import Petition
from projects.aux import _delete_assignation, add_assignation
from projects.forms import ProjectFileForm
from projects.models import Project, Assignation, ProjectInterest, ProjectInterestCategory


@login_required
def join_project(request, slug):
    user = get_user(request)
    project = Project.objects.get(slug=slug)
    context = {
        'project': project,
    }
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']
        receiver = project.admin
        sender = user
        petitions = Petition.objects.all()
        petition_slug = generate_slug(Petition)
        petition = Petition(sender=sender,
                            receiver=receiver, subject=subject,
                            project=project, message=message,
                            slug=petition_slug)
        petition.save()
        messages.success(request, 'Se envió tu solicitud.')
        return redirect('projects:proyecto', slug=slug)
    else:
        return render(request, 'projects/proyecto_unirse.html', context)


@login_required
def delete_assignation(request, slug):
    assignation = Assignation.objects.get(slug=slug)
    assignation_slug = assignation.slug
    project_slug = assignation.project.slug
    messages.warning(request, 'Se quitó a un miembro del proyecto')
    _delete_assignation(request, assignation_slug)
    try:
        return redirect('projects:proyecto', slug=project_slug)
    except:
        return redirect('projects:proyectos')


class ProjectListView(generic.ListView):
    def get(self, request, *args, **kwargs):
        projects = Project.objects.all()
        paginator = Paginator(projects, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        top_categories = InterestCategory.objects.filter(top=True)
        non_top_categories = InterestCategory.objects.filter(top=False)
        context = {
            'non_top_categories': non_top_categories,
            'top_categories': top_categories,
            'page_obj': page_obj,
        }
        return render(request, 'projects/proyectos.html', context)


class ProjectDetailView(generic.View):
    def get(self, request, slug, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request,
                             'Debes iniciar sesión para ver más sobre un proyecto')
            return redirect('core:login')
        user = get_user(request)
        try:
            project = Project.objects.get(slug=slug)
        except:
            return redirect('projects:proyectos')
        assignations = Assignation.objects.filter(project=project)
        author = False
        if user == project.admin:
            author = True
            action_url = project.get_update_project_url
            color = 'warning'
            button = 'Editar'
        else:
            if assignations.filter(user=user).count() is 0:
                received_petitions = Petition.objects.filter(receiver=user).filter(project=project)
                color = 'success'
                print(received_petitions)
                if received_petitions.count() is 0:
                    action_url = project.get_join_project_url
                    button = 'Join'
                else:
                    action_url = received_petitions[0].get_petitions_url
                    button = 'Ver invitación'
                petitions = Petition.objects.filter(
                    sender=user, project=project)
                if petitions.count() is not 0:
                    action_url = petitions[0].get_cancel_petition_url
                    color = 'danger'
                    button = 'Delete request'
            else:
                my_assignation = assignations.filter(user=user)[0]
                action_url = my_assignation.get_delete_assignation_url
                color = 'danger'
                button = 'Quit'

        project_interests = ProjectInterest.objects.filter(project=project)
        admin = Member.objects.filter(user=user)[0]
        context = {
            'object': project,
            'admin': admin,
            'assignations': assignations,
            'author': author,
            'action_url': action_url,
            'color': color,
            'button': button,
            'project_interests': project_interests,
        }
        return render(request, 'projects/proyecto.html', context)


class ProjectNewMembersView(generic.View, LoginRequiredMixin):
    def get(self, request, slug, *args, **kwargs):
        project = Project.objects.get(slug=slug)
        if request.user != project.admin:
            messages.warning('Elemento no está vinculado al usuario.')
            return redirect('projects:proyectos')
        assignations = Assignation.objects.filter(project=project)
        project_interests = ProjectInterest.objects.filter(project=project)
        already_members = []
        for assignation in assignations:
            user = assignation.user
            member = Member.objects.get(user=user)
            already_members.append(member)
        interests = []
        for project_interest in project_interests:
            interests.append(project_interest.interest)
        members = []
        for interest in interests:
            members_interest = MemberInterest.objects.filter(interest=interest)
            for member_interest in members_interest:
                if member_interest.member not in already_members:
                    members.append(member_interest.member)
        paginator = Paginator(members, 18)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'project': project,
            'page_obj': page_obj,
        }
        return render(request, 'projects/proyecto_nuevos_miembros.html', context)


class ProjectInterestView(generic.View):
    def get(self, request, category, interest=None):
        projects = ProjectInterest.objects.filter(category_slug=category)
        current_category = InterestCategory.objects.get(slug=category)
        top_categories = InterestCategory.objects.filter(top=True)
        non_top_categories = InterestCategory.objects.filter(top=False)
        top_interests = Interest.objects.filter(category=current_category).filter(top_category=True)
        non_top_interests = Interest.objects.filter(category=current_category).filter(top_category=False)
        paginator = Paginator(projects, 9)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        if interest is not None:
            projects = projects.filter(interest_slug=interest)
        else:
            projects = ProjectInterestCategory.objects.filter(category=current_category)
        context = {
            'page_obj': page_obj,
            'top_categories': top_categories,
            'non_top_categories': non_top_categories,
            'top_interests': top_interests,
            'non_top_interests': non_top_interests,
        }
        return render(request, 'projects/proyectos_filter.html', context)


# CRUD Projects

def add_project(request):
    if not request.user.is_authenticated:
        messages.warning(request, 'Debes iniciar sesión para ver añadir un proyecto')
        return redirect('core:login')
    if request.method == 'POST':
        user = get_user(request)
        title = request.POST['title']
        summary = request.POST['summary']
        description = request.POST['description']
        project_slug = generate_slug(Project)
        project = Project(admin=user,
                          title=title, summary=summary,
                          description=description, slug=project_slug)
        project.save()
        add_assignation(project, user)
        form = ProjectFileForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
        messages.success(request, '¡Se añadió un proyecto!')
        return redirect('projects:project-add-tags', project_slug=project_slug, category='computacion')
    else:
        form = ProjectFileForm()
        context = {
            'form': form,
        }
        return render(request, 'projects/proyecto_crear.html', context)


@login_required
def update_project(request, slug):
    user = get_user(request)
    project = Project.objects.get(slug=slug)
    if user == project.admin:
        print('view')
        if request.method == 'POST':
            print('post')
            project.title = request.POST['title']
            project.summary = request.POST['summary']
            project.description = request.POST['description']
            project.save()
            form = ProjectFileForm(request.POST, request.FILES, instance=project)
            if form.is_valid():
                form.save()
                messages.success(request, 'Se actualizó la imagen del proyecto.')
            messages.success(request, 'Se actualizó la información del proyecto.')
            return redirect('projects:update-project', slug=project.slug)
        else:
            print('get')
            form = ProjectFileForm()
            context = {
                'project': project,
                'form': form,
            }
            return render(request, 'projects/proyecto_editar.html', context)
    else:

templates/projects/project_add_tags.html
{% extends "base.html" %}

{% block content %}
<br><br><br>
  <section class="pb_section pb_slant-light" id="section-pasos">
    <div class="container">
      <div style="margin-bottom: 10px !important; height: 80px !important;" class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>Proyecto</strong></h5>
          <h2>{{project.title}}</h2>
          <h6><a class="filter" href="{{project.get_absolute_url}}">Ver proyecto</a></h6>
        </div>
      </div>
      <div style="margin-top: 20px !important; margin-bottom: 10px !important; height: 80px !important; text-align: center;" class="row justify-content-center">
        <div class="col-2"></div>
        <div class="col-8">
          <a class="filter text-uppercase text-xs mb-2" href="{% url 'projects:project-delete-tags' slug=project.slug %}">
            Ver los tags de {{project.title}}
        </a>
        </div>
        <div class="col-2"></div>

      </div>
      <div style="margin: auto;" class="row">
        <div id="navbarmobile" class="hide-desktop">
          {% if categories %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorías
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for category in categories %}
              <a class="dropdown-item" href="{% url 'projects:project-add-tags' project_slug=project.slug category=category.slug %}">{{category.name}}</a>
              {% endfor %}
  
            </div>
          </div>
          {% endif %}
          <br>
        </div>
      </div> 
      <div class="row">
        <div class="col-2 border-left hide-mobile">
              
          <!-- Title -->
          <h6 class="title">
            Categorías
          </h6>
    
          <!-- Sidenav -->
          <nav class="sidenav d-flex flex-column mb-5 mb-md-0">
            {% for category in categories %}
            <a class="filter text-uppercase text-xs mb-2" href="{% url 'projects:project-add-tags' project_slug=project.slug category=category.slug %}">
              {{category.name}}
            </a>
            {% endfor %}
          </nav>
        </div>
        <div class="col-2 hide-desktop"></div>
        <div class="col-8">
          <div class="row">
            {% for tag in tags %}
        
        <div class="col-lg-4 col-md- col-sm-6">
          <div class="media d-block pb_feature-v1 text-left">

          <div class="card card-square" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{ tag.name }}</h5>
                  <a href="{% url 'projects:project-add-interest' project_slug=project.slug tag=tag.slug %}" class="btn btn-success">Añadir</a>
                </div>
              </div>
          </div>
        </div>
        {% endfor %}
          </div>
        </div>
        <div class="col-2 border-right">
        </div>
        
      </div>
    </div>
  </section>

{% endblock content %}

templates/projects/proyecto.html
{% extends "base.html" %}

{% block content %}
<section class="pb_section pb_slant-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 mb-5">
          {% if object.image %}
          <img src="{{object.image.url}}" alt="Imagen de {{object.title }}" class="img-fluid">
          {% endif %}
        </div>
        <div class="col-lg-8 pl-md-5 pl-sm-0">
          <div class="row">
            <div class="col">
              <h2>{{ object.title }}</h2>
              <p class="pb_font-20">{{ object.summary }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg">

              <div class="media pb_feature-v2 text-left mb-1 mt-5">
                <div class="pb_icon d-flex mr-3 align-self-start pb_w-15"><i class="ion-ios-bookmarks-outline pb_icon-gradient"></i></div>
                <div class="media-body">
                  <h3 class="mt-2 mb-2 heading">
                      Administrador:
                      <a href={{ admin.get_absolute_url }}>
                          {{ admin.name }}
                      </a>
                  </h3>
                </div>
              </div>

              <div class="media pb_feature-v2 text-left mb-1 mt-5">
                <div class="pb_icon d-flex mr-3 align-self-start pb_w-15"><i class="ion-ios-infinite-outline pb_icon-gradient"></i></div>
                <div class="media-body">
                  <h3 class="mt-2 mb-2 heading">Descripción</h3>
                  <p class="text-sans-serif pb_font-16">{{ object.description }}</p>
                  <!--<p class="text-sans-serif pb_font-16">Creado el {{ object.start_date }}</p>-->
                </div>
              </div>
              <div class="media pb_feature-v2 text-left mb-1 mt-5">
                <div class="pb_icon d-flex mr-3 align-self-start pb_w-15"><i class="ion-ios-infinite-outline pb_icon-gradient"></i></div>
                <div class="media-body">
                  <h3 class="mt-2 mb-2 heading">Intereses relacionados</h3>
                  {% for interest in project_interests %}
                  <p class="text-sans-serif pb_font-16">{{ interest.interest }}</p>
                  {% endfor %}
                </div>
              </div>
              <div class="media text-left mb-1 mt-5">
                <div class="media-body">
                <a href="{{ action_url }}" class="btn btn-{{color}}">{{button}}</a>
                {% if author %}
                <a href="{% url 'projects:project-find-members' slug=object.slug %}" class="btn btn-success">Miembros recomendados</a>
                {% endif %}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>


  <section class="pb_section pb_slant-light" id="section-pasos">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>Miembros de {{ object.title }}</strong></h5>
          <h2>Equipo</h2>
        </div>
      </div>
      <div class="row">
        {% for assignation in assignations %}
        <div class="col-lg-4 col-md- col-sm-6">
          <div class="media d-block pb_feature-v1 text-left">

          <div class="card card-square" style="width: 18rem;">
            {% if assignation.user.member.image %}
                <img class="card-img-top img-fluid" src="{{assignation.user.member.image.url}}" alt="Imagen de {{assignation.user.member.name}}">
              {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{ assignation.user.member.name }}</h5>
                  <p class="card-text">{{ assignation.user.member.summary }} </p>
                  <a href="{{ assignation.user.get_absolute_url }}" class="btn btn-success">Conocer</a>
                  {% if author %}
                  <a href="{{ assignation.get_delete_assignation_url }}" class="btn btn-danger">Borrar</a>
                  {% endif %}
                </div>
          </div>

          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock content %}

templates/projects/proyecto_crear.html
{% extends "base.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div style="margin-top: 200px; margin-bottom: 200px;" class="container">
<form action="{% url 'projects:add-project'%}" method="POST" class="bg-white rounded pb_form_v1" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="mb-4 mt-0 text-center">Proyecto</h2>
    <div class="form-group">
        <input type="text" class="form-control pb_height-50 reverse" maxlength="30" name="title" placeholder="Título">
    </div>
    <div class="form-group">
        <textarea cols="30" rows="1" class="form-control" maxlength="80" name="summary" placeholder="Oneliner del Proyecto"></textarea>
      </div>
      <div class="form-group">
        <textarea cols="30" rows="10" class="form-control" name="description" placeholder="¿De qué trata?"></textarea>
      </div>
      <div class="form-group">
      {{ form }}
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary btn-lg btn-block pb_btn-pill  btn-shadow-blue" value="Crear">
    </div>
</form>
</div>

{% endblock content %}

templates/projects/proyectos.html
{% extends "base.html" %}

{% block content %}
<section class="pb_cover_v3 overflow-hidden cover-bg-opacity text-left  pb_slant-light green-background" id="section-home">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-6">
          <h2 class="heading mb-3">Banco de proyectos</h2>
          <div class="sub-heading">
            <p class="mb-4">¿Quieres ser parte de un grupo de investigación o emprendimiento?</p>
            <p class="mb-4">1. Busca el proyecto que desees</p>
            <p class="mb-4">2. Postula</p>
            <p class="mb-4">3. ¡Sé elegido! </p>
            <br>
            <p class="mb-4">¿Tienes un proyecto? ¡Súbelo aquí!</p>
            <p class="mb-5"><a class="btn btn-success btn-lg pb_btn-pill smoothscroll" href="{% url 'projects:add-project' %}"><span class="pb_font-14 text-uppercase pb_letter-spacing-1">Crear</span></a></p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="anchor" class="pb_section pb_slant-light" id="section-pasos">

    <div class="container">

      <div style="margin-bottom: 10px !important; height: 80px !important;" class="row justify-content-center mb-5">
        <div class="col-md-6 text-center mb-5">
          <h5 class="text-uppercase pb_font-15 mb-2 pb_color-dark-opacity-3 pb_letter-spacing-2"><strong>Iniciativas de la comunidad</strong></h5>
          <h2>Proyectos</h2>
        </div>
      </div>
      <div style="margin: auto;" class="row">
        <div id="navbarmobile" class="hide-desktop">
          {% if top_categories %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorías
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a style="color:#47b55d;" class="dropdown-item" href="{% url 'projects:project-filter' %}">Búsqueda Avanzada</a>
              {% for category in top_categories %}
              <a class="dropdown-item" href="{{category.get_project_category_url}}#anchor-filter">{{category.name}}</a>
              {% endfor %}
  
            </div>
          </div>
          {% endif %}
          <br>
        </div>
      </div>    

      <div class="row">
        
        <div id="sidenavbar" class="col-2 border-left hide-mobile">
          
          <h6><a class="filter text-xs mb-2" href="{% url 'projects:project-filter' %}">Búsqueda Avanzada</a></h6>
          <!-- Title -->
          <h6 class="title">
            Categorías
          </h6>
    
          <!-- Sidenav -->

          <nav class="sidenav d-flex flex-column mb-5 mb-md-0">
            {% for category in top_categories %}
            <a class="filter text-uppercase text-xs mb-2" href="{{category.get_project_category_url}}#anchor-filter">
              {{category.name}}
            </a>
            {% endfor %}
          </nav>
          {% if non_top_categories %}
          <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Otros
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for category in non_top_categories %}
              <a class="dropdown-item" href="{{category.get_project_category_url}}#anchor-filter">{{category.name}}</a>
              {% endfor %}
            </div>
          </div>
          {% endif %}
    
        </div>
        <div id="sidespace" class="col-2 border-left hide-desktop">
        </div>

        <div class="col-8">
          <div class="row">
            {% for project in page_obj %}
            <div class="col-sm-12 col-md-6 col-lg-4">
                <div class="card">
                  {% if project.image %}
                  <img style="margin: auto; height: 200px; width: 200px; max-width: 100%;" class="card-img-top" src="{{project.image.url}}" alt="Card image cap">
                  {% else %}
                  <img style="margin: auto; height: 200px; width: 200px; max-width: 100%;" class="card-img-top" src="..." alt="Card image cap">
                  {% endif %}
                  <div class="card-block">
                        <div class="card-title">{{ project.title }}</div>
                        <div style="font-size: smaller;" class="card-text">
                            {{ project.summary }}
                        </div>
                        <!--<p class="card-text"><small class="text-muted">{{project.start_date}}</small></p>-->
                        <div style="margin: 0 auto; width: 50%;" class="card-text"><a class="btn btn-success" href="{{project.get_absolute_url}}">Ver más</a></div>
                        <br>
                    </div>
                </div>
                <br>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="col-2 border-right">

        </div>
        
      </div>

      <br>
      <br>
      <div style="display: flex; justify-content: center; align-items: center;" class="pagination ali">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a style="color: #47b55d" href="?page=1#anchor">&laquo; first</a>
                <a style="color:#47b55d" href="?page={{ page_obj.previous_page_number }}#anchor">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a style="color:#47b55d" href="?page={{ page_obj.next_page_number }}#anchor">next</a>
                <a style="color:#47b55d" href="?page={{ page_obj.paginator.num_pages }}#anchor">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    
    </div>
  </section>

{% endblock content %}