core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'
urlpatterns = [
    path('', about, name='about'),
    path('register/', newRegister, name='register'),
    path('newRegister/', newRegister, name='newRegister'),
    path('register/verifymail', verify_mail, name='verify_mail'),
    path('register/verifyusername', verify_username, name='verify_username'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('accounts/social/signup/', social_register, name='social-register'),
    path('user-verification/', user_verification, name='user-verification'),
]

elemental/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from elemental import settings

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('members/', include('members.urls', namespace='members')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('notes/', include('notes.urls', namespace='notes')),
    path('el3m3nt4l/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path

from members.views import *

app_name = 'members'
urlpatterns = [
    path('miembros/', MemberListView.as_view(), name='miembros'),
    path('miembros/skills/', MemberSkillView.as_view(), name='miembros-skills'),
    path('miembros/skills/<slug:category>/', MemberSkillView.as_view(), name='miembros-skills-categoria'),
    path('miembros/skills/<slug:category>/<slug:skill>', MemberSkillView.as_view(), name='miembros-skills-particular'),
    path('miembros/intereses/', MemberInterestView.as_view(), name='miembros-intereses'),
    path('miembros/intereses/<slug:category>/', MemberInterestView.as_view(), name='miembros-intereses-categoria'),
    path('miembros/intereses/<slug:category>/<slug:interest>', MemberInterestView.as_view(), name='miembros-intereses-particular'),
    path('miembros/filtro/', MemberAdvancedFilterView.as_view(), name='member-filter'),
    path('miembro/<slug>/', MemberDetailView.as_view(), name='miembro'),
    path('add-tags/<slug:designation>/<slug:category>', MemberAddTagView.as_view(), name='add-tags'),
    path('delete-tags/', MemberDeleteTagView.as_view(), name='delete-tags'),
    path('add-skill/<slug:tag>/', add_skill, name='add-skill'),
    path('delete-interest/<slug:tag>', delete_interest, name='delete-interest'),
    path('add-interest/<slug:tag>/', add_interest, name='add-interest'),
    path('delete-skill/<slug:tag>', delete_skill, name='delete-skill'),
    path('update-user/', update_user, name='update-user'),
    path('getSkills/',  get_skill_for_register, name='get_skill_for_register'),
    path('getInterest/', get_interest_for_register, name='get_skill_for_register'),
]

notes/urls.py
from django.urls import path

from notes.views import *

app_name = 'notes'
urlpatterns = [
    path("peticiones/", PetitionListView.as_view(), name="peticiones"),
    path("authorize-petition/<slug>/", authorize_petition, name='authorize-petition'),
    path("deny-petition/<slug>/", deny_petition, name='deny-petition'),
    path("cancel-petition/<slug>/", cancel_petition, name='cancel-petition'),
    path("delete-notification/<slug>/", delete_notification, name="delete-notification"),
    path("miembro/<slug>/send-invitation/", send_invitation_project, name='send-invitation-project'),
]

projects/urls.py
from django.urls import path

from projects.views import *

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='proyectos'),
    path('intereses/', ProjectListView.as_view(), name='proyectos-intereses'),
    path('intereses/<slug:category>/', ProjectInterestView.as_view(), name='proyectos-intereses-categoria'),
    path('intereses/<slug:category>/<slug:interest>/', ProjectInterestView.as_view(), name='proyectos-intereses-particular'),
    path('add-project/', add_project, name='add-project'),
    path('update-project/<slug>/', update_project, name='update-project'),
    path('delete-project/<slug>/', delete_project, name='delete-project'),
    path('project-add-tags/<slug:project_slug>/<slug:category>', ProjectAddTagView.as_view(), name='project-add-tags'),
    path('project-add-interest/<slug:project_slug>/<slug:tag>/', project_add_interest, name='project-add-interest'),
    path('project-delete-tags/<slug>', ProjectDeleteTagView.as_view(), name='project-delete-tags'),
    path('project-delete-interest/<slug:project_slug>/<slug:tag>/', project_delete_interest, name='project-delete-interest'),
    path('proyectos/filtro/', ProjectAdvancedFilterView.as_view(), name='project-filter'),
    path('delete-assignation/<slug>/', delete_assignation, name='delete-assignation'),
    path('join-project/<slug>/', join_project, name='join-project'),
    path('<slug>/', ProjectDetailView.as_view(), name='proyecto'),
    path('<slug>/miembros/', ProjectNewMembersView.as_view(), name='project-find-members'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>Elemental</title>
		<meta name="description" content="Plataforma para la comunidad de investigación y emprendimiento Elemental.">
		<meta name="keywords" content="Comunidad, Bioingeniería, Plataforma, Proyectos, Investigación, Emprendimiento">

    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600|Montserrat:200,300,400" rel="stylesheet">
    <link rel='stylesheet' href='https://cdn3.devexpress.com/jslib/20.1.4/css/dx.common.css'>
    <link rel='stylesheet' href='https://cdn3.devexpress.com/jslib/20.1.4/css/dx.light.css'><link rel="stylesheet" href="/static/css/newRegister.css">
    <link rel="stylesheet" href="/static/css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="/static/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/fonts/law-icons/font/flaticon.css">

    <link rel="stylesheet" href="/static/fonts/fontawesome/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/fb38ff9278.js" crossorigin="anonymous"></script>
    

    <link rel="stylesheet" href="/static/css/slick.css">
    <link rel="stylesheet" href="/static/css/slick-theme.css">

    <link rel="stylesheet" href="/static/css/helpers.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/landing-2.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
        <style>

            @import url(https://fonts.googleapis.com/css?family=Roboto:500);

            .green-background {
   background: linear-gradient(to right top, #a4de02, #71cb43, #47b55d, #2d9e6b, #2e856e) !important;
}

.green-backgroundb {
  background-image: linear-gradient(to right top, #2e856e, #2d9e6b, #47b55d, #71cb43, #a4de02) !important;   
}


.nav-link{
  color: #47b55d !important;
}
.pb_navbar.scrolled.pb_scrolled-light ul li a.active {
  color: #47b55d !important;
}
.navbar-brand{
  color: #47b55d !important;
}
@media screen and (min-width:768px) {
  .hide-desktop {
    display: none;
  }
}
@media screen and (max-width:768px) {
  .hide-mobile {
    display: none;
  }
}
.navbar {
  background-color: rgba(0,0,0,0.6);
}
.pb_navbar .navbar-nav {
  background-color: rgba(0,0,0,0);
}
.section-top {
    box-sizing: border-box;
    text-align: center !important;
}

a.filter {
  color: #47b55d !important;
}

img.card-img-top {
  max-height: 200px !important;
  max-width: 200px !important;
}
div.card-square {
  max-height: 400px !important;
  max-width: 200px !important;
}
.google-btn {
  width: 196px;
  height: 42px;
  background-color: #4285f4;
  border-radius: 2px;
  box-shadow: 0 3px 4px 0 rgba(0,0,0,.25);
}
.google-icon-wrapper {
    position: absolute;
    margin-top: 1px;
    margin-left: 1px;
    width: 40px;
    height: 40px;
    border-radius: 2px;
    background-color: #fff;
  }
  .google-icon {
    position: absolute;
    margin-top: 11px;
    margin-left: 11px;
    width: 18px;
    height: 18px;
  }
  .btn-text {
    float: right;
    margin: 11px 11px;
    padding: 0px 0px 11px 0px;
    color: #fff;
    font-size: 14px;
    letter-spacing: 0.2px;
    font-family: "Roboto";
  }
  .google-btn:hover {
    box-shadow: 0 0 6px #4285f4;
  }
  .google-btn:active {
    background: #1669F2;
  }

footer {
  left: 0;
  bottom: 0;
  width: 100%;
  text-align: center;
}


        </style>
	</head>
	<body data-spy="scroll" data-target="#pb-navbar" data-offset="200">

    <nav class="navbar navbar-expand-lg navbar-dark pb_navbar pb_scrolled-light" id="pb-navbar">
      <div class="container">
        <a class="navbar-brand" href="/">Elemental</a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#probootstrap-navbar" aria-controls="probootstrap-navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="ion-navicon"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="probootstrap-navbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'core:about'%}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'projects:proyectos'%}">Proyectos</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'members:miembros'%}">Miembros</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{{ user.get_absolute_url }}">Mi perfil</a></li>
            {% endif %}
            {% if user.has_notifications %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'notes:peticiones' %}">
                <b>Notificaciones</b>
                <i class="fas fa-exclamation"></i>
            </a>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'notes:peticiones'%}">Notificaciones</a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item cta-btn ml-xl-2 ml-lg-2 ml-md-0 ml-sm-0 ml-0"><a class="nav-link" href="/logout"><span class="pb_rounded-4 px-4">Logout</span></a></li>
            {% else %}
            <li class="nav-item cta-btn ml-xl-2 ml-lg-2 ml-md-0 ml-sm-0 ml-0"><a class="nav-link" href="/login"><span class="pb_rounded-4 px-4">Login</span></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %}
    <br><br><br> 
    {% for message in messages %}
      <div class = "alert alert-{{ message.tags }}">
         {{ message }}
      </div>
    {% endfor %}
    {% endif %}
      

    <!-- END nav -->
    {% block content %}
    {% endblock content%}


      <br><br>
    <footer class="pb_footer bg-light" role="contentinfo">
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <p class="pb_font-14">&copy; 2019. All Rights Reserved. <br>  <a style="color: #71cb43" href="https://uicookies.com/bootstrap-html-templates/">Bootstrap Templates</a> by uiCookies</p>
          </div>
        </div>
      </div>
    </footer>


    <script src="/static/js/jquery.min.js"></script>

    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/slick.min.js"></script>
    <script src="/static/js/jquery.mb.YTPlayer.min.js"></script>

    <script src="/static/js/jquery.waypoints.min.js"></script>
    <script src="/static/js/jquery.easing.1.3.js"></script>

    <script src="/static/js/main.js"></script>
    <!-- partial -->
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/cldrjs/0.4.4/cldr.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/cldrjs/0.4.4/cldr/event.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/cldrjs/0.4.4/cldr/supplemental.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/cldrjs/0.4.4/cldr/unresolved.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/globalize/1.1.1/globalize.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/globalize/1.1.1/globalize/message.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/globalize/1.1.1/globalize/number.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/globalize/1.1.1/globalize/currency.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/globalize/1.1.1/globalize/date.min.js'></script>
    <script src='https://cdn3.devexpress.com/jslib/20.1.4/js/dx.all.js'></script><script  src="/static/js/newRegister.js"></script>



	</body>
</html>